# Generated by Django 4.1.7 on 2023-03-11 10:23

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(default=0, max_length=10, validators=[django.core.validators.MinLengthValidator(10, 'Phone number should be 10 digits long')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(default=0, max_length=6, validators=[django.core.validators.MinLengthValidator(6, 'OTP should be 6 digits long')]),
            preserve_default=False,
        ),
    ]
