# Generated by Django 4.1.7 on 2023-03-12 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_created_user_number_user_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10, 'Phone number should be 10 digits long')]),
        ),
    ]
